export const waterDemandFactors = {
  "Metro Elevated Stations": {
    "Occupancy (passengers)": 30,
    "Occupancy (staff)": 45,
    Cleaning: 6,
    Gardening: 5,
  },
  "Metro Underground Stations": {
    "Occupancy (passengers)": 30,
    "Occupancy (staff)": 45,
    Cleaning: 5,
    Gardening: 5,
    "AC Make-up water": 6,
  },
  "Residential Buildings": {
    Occupancy: 150,
    Cleaning: 5,
    Gardening: 5,
  },
  "Office Buildings": {
    "Occupancy (employees)": 50,
    "Occupancy (visitors)": 50,
    Cleaning: 3,
    Gardening: 5,
    "AC Make-up": 4,
    Kitchen: 8,
  },
  Hotels: {
    "Occupancy (visitors)": 200,
    "Occupancy (employees)": 100,
    Cleaning: 5,
    Gardening: 5,
    Kitchen: 25,
    Spa: 5,
    "Swimming Pool": 5,
    "AC Make-up": 6,
  },
  "Data Centers": {
    Occupancy: 20,
    "AC Make-up": 15,
    Cleaning: 1,
    Gardening: 5,
    Kitchen: 25,
  },
  "Shopping Malls": {
    "Occupancy (visitors)": 50,
    "Occupancy (staff)": 30,
    "Food Court": 15,
    Kitchen: 15,
    Cleaning: 5,
    Gardening: 5,
    "AC Make-up": 6,
    "Car Washing": 15,
  },
  Gym: {
    Occupancy: 90,
    Cleaning: 5,
    Gardening: 5,
  },
  Salon: {
    "Occupancy (visitors)": 100,
    "Occupancy (staff)": 50,
    Cleaning: 3,
    Gardening: 5,
    Spa: 5,
  },
  "Car Showroom": {
    "Occupancy (staff)": 30,
    "Occupancy (visitors)": 20,
    "Car Washing": 150,
    Cleaning: 3,
    Gardening: 5,
  },
};
